import './globals.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from './nav/page';
import Footer from './footer/page';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Nav />
      <main>{children}</main>
      <Footer />
    </>
  )
}
